/** Eventos de seguridad auditados. */
export enum AuditEvent {
  LOGIN_SUCCESS = 'LOGIN_SUCCESS',
  LOGIN_FAILED = 'LOGIN_FAILED',
  LOGOUT = 'LOGOUT',
  REGISTER = 'REGISTER',
  CHANGE_PASSWORD = 'CHANGE_PASSWORD',
  PRODUCTION_ORDER_DELETED = 'PRODUCTION_ORDER_DELETED',
  PAGO_DELETED = 'PAGO_DELETED',
}
