/** Eventos de seguridad auditados. */
export enum AuditEvent {
  LOGIN_SUCCESS = 'LOGIN_SUCCESS',
  LOGIN_FAILED = 'LOGIN_FAILED',
  LOGOUT = 'LOGOUT',
  REGISTER = 'REGISTER',
  CHANGE_PASSWORD = 'CHANGE_PASSWORD',
  PRODUCTION_ORDER_DELETED = 'PRODUCTION_ORDER_DELETED',
  PAGO_DELETED = 'PAGO_DELETED',
  MEMBER_ROLE_CHANGED = 'MEMBER_ROLE_CHANGED',
  MEMBER_REMOVED = 'MEMBER_REMOVED',
  INGREDIENT_PRICE_UPDATED = 'INGREDIENT_PRICE_UPDATED',
  FORMULATION_UPDATED = 'FORMULATION_UPDATED',
  ORGANIZATION_SETTINGS_UPDATED = 'ORGANIZATION_SETTINGS_UPDATED',
  PASSWORD_RESET_REQUESTED = 'PASSWORD_RESET_REQUESTED',
  PASSWORD_RESET_COMPLETED = 'PASSWORD_RESET_COMPLETED',
}
